WebShop/WebShop/Controllers/CatsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Hosting.Internal;
using Microsoft.VisualBasic;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebShop.Domain;
using WebShop.Domain.Entities.Products;
using WebShop.Models;
using WebShop.Models.Validation;

namespace WebShop.Controllers
{
    public class CatsController : Controller
    {
        private readonly AppEFContext _context;
        private readonly IMapper _mapper;
        private IHostEnvironment _host;

        public CatsController(AppEFContext context, IMapper mapper, IHostEnvironment host)
        {
            _context = context;
            _mapper = mapper;
            _host = host;
        }
        public IActionResult Index(SearchCatModel searchCat,int currentPage=0)
        {
            CatsIndexModel model = new();
           
            //кількість записів на сторінці.
            model.Pagination.ItemOnPage = 2;
            var query = _context.Cats.AsQueryable();

            if(!string.IsNullOrEmpty(searchCat.Name))
            {
                query = query.Where(y => y.Name.Contains(searchCat.Name));
            }

            //var model = _context.Cats.Select(x => _mapper.Map<CatVM>(x)).ToList();

            //загальна кількість елементів.
            model.Pagination.Count = query.Count();
            //поточна сторінка.
            model.Pagination.CurrentPage = currentPage == 0 ? 1 : currentPage;
           
            query = query
                .OrderBy(x=>x.Name)
                .Skip((model.Pagination.CurrentPage - 1) * model.Pagination.ItemOnPage).Take(model.Pagination.ItemOnPage);

            //список елементів,які будуть розбиті по сторінкам.
            model.Cats= query.Select(x => _mapper.Map<CatVM>(x)).ToList();
           
           
            model.Search = searchCat;

            if (model.Pagination.CurrentPage > model.Pagination.TotalPages)
            {
                model.Pagination.CurrentPage = model.Pagination.TotalPages;
            }
            return View(model);
            
        }

        [HttpGet]
       // [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]       
        //[Authorize(Roles = "Admin")]
        public async Task <IActionResult> Create(CatsValidationModel cats)
        {

            if (!ModelState.IsValid)
                return View(cats);

            string fileName = string.Empty;

            if(cats.Image!=null)
            {
                var ext = Path.GetExtension(cats.Image.FileName);
                fileName = Path.GetRandomFileName() + ext;
                var dir = Path.Combine(Directory.GetCurrentDirectory(), "images");

                var filePath = Path.Combine(dir, fileName);

                using (var stream = System.IO.File.Create(filePath))
                {
                    await cats.Image.CopyToAsync(stream);
                }
            }
            
            Cat cat = new Cat
            {
                Name = cats.Name,
                Price=cats.Price,
                Birthday=cats.BirthDay,
                Image=fileName,
                DateCreate=DateTime.Now
            };


            _context.Cats.Add(cat);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

       [HttpGet]
       //Повертає форму з даними об"єкта,який буде відредагований.
        public IActionResult Edit(long id)
        {
            CatsValidationModel cat = new CatsValidationModel();
            var res = _context.Cats.FirstOrDefault(x => x.Id == id);
            if (res.Image != null)
            {
                //var ext = Path.GetExtension(res.Image);
                var nam = Path.GetFileName(res.Image);
                var dir = Path.Combine(Directory.GetCurrentDirectory(), "images");

                var filePath = Path.Combine(dir, nam);
                using (var stream = System.IO.File.OpenRead($"{filePath}"))
                {
                    var res_image = new FormFile(stream, 0, stream.Length, null, Path.GetFileName(stream.Name));                  

                    cat.Name = res.Name;
                    cat.Price = res.Price;
                    cat.BirthDay = res.Birthday;
                    cat.Image = res_image;                    
                }            
                               
            }

            return View(cat);
        }

        [HttpPost]
        //Отримує відредаговані дані у вигляді об"єкта CatsValidationModel.
        public async Task <IActionResult> Edit(long id, CatsValidationModel cat)
        {

            if (ModelState.IsValid)
            {
                var res = _context.Cats.FirstOrDefault(x => x.Id == id);
                res.Name = cat.Name;
                res.Birthday = cat.BirthDay;

                string fileName = string.Empty;

                if (cat.Image != null)
                {
                    var ext = Path.GetExtension(cat.Image.FileName);
                    fileName = Path.GetRandomFileName() + ext;
                    var dir = Path.Combine(Directory.GetCurrentDirectory(), "images");

                    var filePath = Path.Combine(dir, fileName);

                    using (var stream = System.IO.File.Create(filePath))
                    {
                        await cat.Image.CopyToAsync(stream);
                    }
                    var oldImage = res.Image;
                    string fol = "\\images\\";
                    string contentRootPath = _host.ContentRootPath + fol + oldImage;

                    if (System.IO.File.Exists(contentRootPath))
                    {
                        System.IO.File.Delete(contentRootPath);
                    }
                    res.Image = fileName;
                }             

                res.Price = cat.Price;
                _context.SaveChanges();
               
            }
            return RedirectToAction("Index");
        }


        //[HttpGet]
        //[ActionName("Delete")]

        //public IActionResult DeleteV(long id)
        //{
        //    var catToDelete = _context.Cats.FirstOrDefault(x => x.Id == id);
        //    if (catToDelete != null)
        //    {
        //        return View(catToDelete);
        //    }
        //    return NotFound();
        //}

        [HttpPost]
        public IActionResult Delete(long id)
        {
            var catDel = _context.Cats.FirstOrDefault(x => x.Id == id);
            if(catDel!=null)
            {
                var name = catDel.Image;
               // var exta = Path.GetExtension(catDel.Image);
                string folder = "\\images\\";
                string contentRootPath = _host.ContentRootPath + folder + name;
               
                if (System.IO.File.Exists(contentRootPath))
                {
                    System.IO.File.Delete(contentRootPath);
                }

                _context.Cats.Remove(catDel);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
           return NotFound();
        }
    }
}

WebShop/WebShop/ViewComponents/NavBarUserViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebShop.Domain.Entities.Identity;
using WebShop.Models;

namespace WebShop.ViewComponents
{
    [Authorize]
    public class NavBarUserViewComponent:ViewComponent
    {
        private readonly UserManager<AppUser> _userManager;
       
        public NavBarUserViewComponent(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
           
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            UserNavbarInfoViewModel model = new UserNavbarInfoViewModel
            {
                Name = user.UserName,
                Image = user.ImageProfile
            };           
                     
            return View("_UserNavbarInfo", model);
        }

    }
}

WebShop/WebShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebShop</title>  
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Домашня</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Колись щось буде</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cats" asp-action="Index">Список котів</a>
                        </li>
                    </ul>




                </div>
                <div >
                    @await Html.PartialAsync("_LoginInfo")
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Власюк Н.С. - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   
<script src="~/lib/jquery/jquery.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebShop/WebShop/Views/Shared/_LoginInfo.cshtml
<ul class="navbar-nav ml-4 ">

    @*якщо користувач авторизувався успішно*@
    @if (User.Identity.IsAuthenticated)
    {
        @if (User.IsInRole("Admin"))
         {
            <li class="nav-item ml-5">
                <a class="nav-link text-light fw-bold text-decoration-underline text-center  " 
                   style="font-size:90%"
                   asp-area="admin" 
                   asp-controller="Ecommerce" 
                   asp-action="Orders">Admin panel</a>
            </li>

         }
            @await Component.InvokeAsync("NavBarUser")
       
            <li class="nav-item">

                @using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logout" }))
                {
                    
                    <a class="nav-link" href="#"
                       onclick="document.getElementById('logout').submit();">
                        Вихід <i class="fa fa-sign-out" aria-hidden="true"></i>
                    </a>
                }

            </li>
}
@* в іншому ж випадку на вибір пункти меню для входу чи реєстрації. *@
else
{

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Вхід</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Registration">Реєстрація</a>
    </li>

}

</ul>