WebShop/WebShop/Areas/Admin/Controllers/DashboardsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebShop.Areas.Admin.Controllers
{
    [Area("admin")]
    public class DashboardsController : Controller
    {
        public IActionResult Dashboard_1()
        {
            return View();
        }

        public IActionResult Dashboard_2()
        {
            return View();
        }

        public IActionResult Dashboard_3()
        {
            return View();
        }

        public IActionResult Dashboard_4()
        {
            return View();
        }

        public IActionResult Dashboard_4_1()
        {
            return View();
        }

        public IActionResult Dashboard_5()
        {
            return View();
        }
    }
}

WebShop/WebShop/Areas/Admin/Controllers/EcommerceController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.WebPages.Html;
using WebShop.Areas.Admin.Models;
using WebShop.Domain;
using WebShop.Domain.Entities.Identity;

namespace WebShop.Areas.Admin.Controllers
{
    [Area("admin")]
    public class EcommerceController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<AppRole> _roleManager;
        private readonly AppEFContext _appEF;
        private IPasswordHasher<AppUser> _passwordHasher;

        public EcommerceController(UserManager<AppUser> userManager,
            RoleManager<AppRole> roleManager,
            AppEFContext appEF,
            IPasswordHasher<AppUser> passwordHasher)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _appEF = appEF;
            _passwordHasher = passwordHasher;
        }              


        public async Task <IActionResult> Orders()
        {
            #region Перший варіант виводу на сторінці всіх користувачів.
            //всі ролі.
            //var rol = _roleManager.Roles.ToList();           
            //var allusers = _userManager.Users.ToList();
            //var t = new List<AppRole>();

            //foreach (var rolea in rol)
            //{            
            //    var rolesa = await _userManager.GetUsersInRoleAsync(rolea.Name);              
            //    t.Add(rolea);             

            //}          

            //RolesViewModel model = new RolesViewModel();            

            //var roless = new List<string>();
            //var userss = new List<AppUser>();
            //for (int i = 0; i < t.Count; i++)
            //{
            //    var role = _appEF.Roles.SingleOrDefault(s => s.Name.Contains((t[i].Name)));
            //    var usersInRole = _appEF.Users.Where(m => m.UserRoles.Any(r => r.RoleId == role.Id)).ToList();
            //    roless.Add(role.Name);
            //    userss.AddRange(usersInRole);    

            //}
            //model.Name = userss;
            //model.Role = roless;  
            //return View(model);

            //=============До уваги не брати============================
            // var role = _appEF.Roles.SingleOrDefault(m => m.Name == "User");
            //var usersInRole = _appEF.Users.Where(m => m.UserRoles.Any(r => r.RoleId == ro.Id)).ToList();
            //===========================================

            #endregion

            #region Display all users with their roles.

            var usersWithRoles = (from user in _appEF.Users
                                  select new
                                  {
                                      UserId = user.Id,
                                      Username = user.UserName,
                                      Email = user.Email,
                                      RoleNames = (from userRole in user.UserRoles
                                                   join role in _appEF.Roles on userRole.RoleId
                                                   equals role.Id
                                                   select role.Name).ToList()
                                  }).ToList().Select(p => new ViewUserRolesModel()

                                  {
                                      UserId = p.UserId,
                                      Username = p.Username,
                                      Email = p.Email,
                                      Role = string.Join(",", p.RoleNames)
                                  });

            return await Task.FromResult(View(usersWithRoles));

            #endregion
        }




        #region Delete

        public async Task<IActionResult> Delete(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Orders", "Ecommerce", new { area = "Admin" }, null);
                else
                    ModelState.AddModelError("", "Не вдалося видалити");
            }
            else               
                ModelState.AddModelError("", "Користувач не знайдений");

            return View("Orders", _userManager.Users);
        }

        #endregion

        #region Add new user
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(AddUserByAdminModel addUser)
        {
            var user = await _userManager.FindByEmailAsync(addUser.Email);
            
            //строчка для файлу фото профіля.            
            string fileNameUser = string.Empty;

            //якщо фото обрано:
            if (addUser.Image != null)
            {
                //розширення
                var ext = Path.GetExtension(addUser.Image.FileName);
                //імя файла з розширенням.
                fileNameUser = Path.GetRandomFileName() + ext;
                //директорія,де знаходитиметься файл.
                var dir = Path.Combine(Directory.GetCurrentDirectory(), "images");
                //повний шлях до фото.
                var filePath = Path.Combine(dir, fileNameUser);

                using (var stream = System.IO.File.Create(filePath))
                {
                    await addUser.Image.CopyToAsync(stream);
                }
            }
           
            //якщо користувач вже існує,то виводимо попередження.
            if (user != null)
            {
                ModelState.AddModelError("Email", " Користувач з такими даними вже існує ");
            }
            //якщо введені валідні дані для реєстрації користувача:
            if (ModelState.IsValid)
            {
                user = new AppUser
                {
                    Email = addUser.Email,
                    UserName = addUser.Email,
                    ImageProfile = fileNameUser
                };
                var role = new AppRole
                {
                    Name = "User"
                };

                //створили користувача.
                var result = await _userManager.CreateAsync(user, addUser.Password);

                if (result.Succeeded)
                {
                    //додали роль користувачу.
                    await _userManager.AddToRoleAsync(user, "User");
                    //і перепаравили на головну сторінку з переліком користувачів.
                    return RedirectToAction("Orders", "Ecommerce", new { area = "Admin" }, null);
                }
                else
                {
                    ModelState.AddModelError("", "Помилка.");
                }
            }
            return View(addUser);
        }
        #endregion

        #region Edit
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            string userRole = (await _userManager.GetRolesAsync(user)).FirstOrDefault();
            UserWithRoles editUser = new UserWithRoles()
            { 
             UserId=user.Id,
             UserName=user.UserName,
              Email=user.Email,
              Image=user.ImageProfile,
              Role=userRole
            };       
                     
            List<string> roles = _roleManager.Roles.Select(r => r.Name).ToList();
            ViewBag.Roles = roles;
            
            return View(editUser);               
            
        }


        [HttpPost]        
        public async Task<IActionResult> Edit(string id,ChangeRoleModel changeRole)
        {
            AppUser user = await _userManager.FindByIdAsync(id);

            if (!string.IsNullOrEmpty(changeRole.OldRole))
            {
                IdentityResult delRole = await _userManager.RemoveFromRoleAsync(user,changeRole.OldRole);
            }
            IdentityResult addRole = await _userManager.AddToRoleAsync(user, changeRole.Role);


            if (!string.IsNullOrEmpty(changeRole.Email))
                user.Email = changeRole.Email;
            else
                ModelState.AddModelError("", "Email cannot be empty");

            if (!string.IsNullOrEmpty(changeRole.UserName))
                user.UserName = changeRole.UserName;
            else
                ModelState.AddModelError("", "Name cannot be empty");
            if (user.ImageProfile != null)
                user.ImageProfile = changeRole.Image;
            else
                ModelState.AddModelError("", "Photo cannot be empty");

            if (!string.IsNullOrEmpty(changeRole.Email) && !string.IsNullOrEmpty(changeRole.UserName))
            {
                IdentityResult result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Orders", "Ecommerce", new { area = "admin" });
                else
                    ModelState.AddModelError("", "Error");
            }
            return RedirectToAction("Orders", "Ecommerce", new { area = "admin" });
            
        }
        #endregion
    }
}

WebShop/WebShop/Areas/Admin/Views/Ecommerce/Create.cshtml
@model WebShop.Areas.Admin.Models.AddUserByAdminModel

@using WebShop.Domain.Entities.Identity


@{
    ViewData["Title"] = "Додати нового користувача";
}


<div class="row">
    <div class="col-md-6 offset-md-3 ">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label "asp-area="admin" ></label>
        <input asp-for="Email" class="form-control" asp-area="admin"/>
        <span asp-validation-for="Email" class="text-danger "></span>              
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"asp-area="admin"></label>
        <input asp-for="Password" class="form-control" asp-area="admin"/>
        <span asp-validation-for="Password" class="text-danger"></span>               
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"asp-area="admin" ></label>                    
                <div>
                    <img id="profilePicture" style="width:150px;height:150px; object-fit:cover">
                </div>
                <input asp-for="Image" type="file" 
                       class="form-control"
                       onchange="document.getElementById('profilePicture').src = window.URL.createObjectURL(this.files[0])">               
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" formmethod="post"  />
            </div>
        </form>
    </div>

</div>

WebShop/WebShop/Areas/Admin/Views/Ecommerce/Edit.cshtml
@model WebShop.Areas.Admin.Models.UserWithRoles
@using WebShop.Domain.Entities.Identity
@{
    ViewData["Title"] = "Редагувати дані";
}

<h1>@ViewData["Title"]</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label" asp-area="admin"></label>
                <div>
                    <img id="profilePicture" src="/images/@Model.Image" style="width: 150px; height: 150px;">
                </div>
                <input asp-for="Image" type="file"
                       class="form-control" src="/images/@Model.Image" object-fit: cover"
                       onchange="document.getElementById('profilePicture').src = window.URL.createObjectURL(this.files[0])">
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="hidden" name="OldRole" value="@Model.Role" />
                <input list="RoleList" asp-for="Role">
                <datalist id="RoleList">
                    @foreach (var role in ViewBag.Roles as List<string>) 
                    {               
                   
                        <option value="@role"></option>
                    
                    }
                </datalist>               

            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти зміни" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Orders" asp-controller="Ecommerce" asp-area="admin">Back to List</a>
</div>










@*<h4>CatEditModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="NameUser" class="control-label"></label>
                    <input asp-for="NameUser" class="form-control" />
                    <span asp-validation-for="NameUser" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="control-label" asp-area="admin"></label>
                    <div>
                        <img id="profilePicture"src="/images/@Model.Image"  style="width: 150px; height: 150px;">
                    </div>
                    <input asp-for="Image" type="file"
                           class="form-control" src="/images/@Model.Image"  object-fit: cover"
                           onchange="document.getElementById('profilePicture').src = window.URL.createObjectURL(this.files[0])">
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="RoleUser" class="control-label"></label>
            <input asp-for="RoleUser" class="form-control" />
            <span asp-validation-for="RoleUser" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <input type="submit" value="Зберегти зміни" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebShop/WebShop/Areas/Admin/Views/Ecommerce/Orders.cshtml
@model IEnumerable< WebShop.Areas.Admin.Models.ViewUserRolesModel>
@using WebShop.Domain.Entities.Identity

@{
    ViewData["Title"] = "Users";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Користувачі</h2>
        <ol class="breadcrumb">
            <li>
                @*<a href="@Url.Action("Dashboard_1", "Dashboards")">Щось буде...</a>*@
            </li>
            <li>
                <a asp-area="admin" class="text-success"  asp-action="Create" asp-controller="Ecommerce">Create</a>
            </li>               
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight ecommerce">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">

                    <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
                        <thead>
                            <tr>

                                <th>User ID</th>
                                <th data-hide="phone">Name</th>
                                <th data-hide="phone">E-mail</th>
                                <th class="text-right">Role</th>
                                <th class="text-right">Action</th>
                               
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var user in Model)
                            {
                                <tr>
                                    <td>
                                        @user.UserId
                                    </td>
                                    <td>
                                        @user.Username
                                    </td>
                                    <td>
                                        @user.Email
                                    </td>
                                    <td>
                                        @user.Role
                                    </td>

                                    <td class="text-right">
                                        <div class="btn-group">
                                            @*<a href="Create" asp-area="admin" class="text-success"
                                               asp-action="Create"
                                               asp-controller="Ecommerce">Create</a>*@
                                            &nbsp;&nbsp;&nbsp;
                                            <a  class="text-success"                                                
                                                href="Edit/@user.UserId">Edit</a>
                                            &nbsp;&nbsp;&nbsp;
                                            <a href="Delete/@user.UserId" 
                                               class="text-success">Deleted</a>

                                        </div>
                                    </td>
                                </tr>
                            }
                          
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="7">
                                    <ul class="pagination pull-right"></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
        </div>
    </div>


</div>

@section Styles {
    <environment names="Development">
        <link rel="stylesheet" href="~/template/lib/footable/css/footable.core.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/template/lib/footable/css/footable.core.min.css" />
    </environment>
}

@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/template/lib/footable/dist/footable.all.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.footable').footable();
        });
    </script>
}